/*
 * Copyright (c) 2021-2025 Snowplow Analytics Ltd. All rights reserved.
 *
 * This program is licensed to you under the Apache License Version 2.0,
 * and you may not use this file except in compliance with the Apache License Version 2.0.
 * You may obtain a copy of the Apache License Version 2.0 at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Apache License Version 2.0 is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Apache License Version 2.0 for the specific language governing permissions and limitations there under.
 */
package com.snowplowanalytics.snowplow.eventgen

import org.scalacheck.Gen

/** Deterministic user selection with power law distribution.
  *
  * Implements Pareto-like distribution where a small fraction of users ("hot" users) generate the majority of events,
  * mimicking real-world user engagement patterns.
  */
object UserDistribution {

  /** Fraction of the user pool considered "hot" (highly active). Default 0.2 (20%) follows the Pareto principle where
    * top 20% of users generate 80% of activity.
    */
  val DefaultHotFraction: Double = 0.2

  /** Fraction of total events generated by hot users. Default 0.8 (80%) follows the Pareto principle.
    */
  val DefaultHotEventFraction: Double = 0.8

  /** Exponent controlling concentration within the hot zone.
    *
    * Applied as: position = (uniform_random / hotEventFraction) ^ exponent
    *
    * Lower values create steeper power-law curves with heavier concentration at the top:
    *   - 1.0: Linear distribution within hot zone (uniform)
    *   - 0.5: Square root, moderate concentration
    *   - 0.15: Very heavy concentration, top users dominate significantly
    *
    * Value of 0.15 creates realistic "superuser" behavior where the top few users generate disproportionately more
    * events than others in the hot zone.
    */
  val HotZoneConcentrationExponent: Double = 0.15

  /** Select user using power law distribution (80/20 Pareto principle). Top 20% of users generate ~80% of events.
    *
    * O(1) time complexity, works efficiently with large identity pools.
    *
    * @param numUsers
    *   Total number of identities in the pool
    * @param hotFraction
    *   Fraction of identities that are "hot" (default 0.2 = 20%)
    * @param hotEventFraction
    *   Fraction of events from hot identities (default 0.8 = 80%)
    * @return
    *   Gen that produces identity IDs following power law distribution
    */
  def selectPowerLaw(
    numUsers: Long,
    hotFraction: Double = DefaultHotFraction,
    hotEventFraction: Double = DefaultHotEventFraction
  ): Gen[Long] =
    Gen.choose(0.0, 1.0).map { u =>
      if (u < hotEventFraction) {
        // 80% of events -> top 20% of identities
        val hotPoolSize = (numUsers.toDouble * hotFraction).toLong
        val position    = Math.pow(u / hotEventFraction, HotZoneConcentrationExponent)
        (position * hotPoolSize.toDouble).toLong
      } else {
        // 20% of events -> bottom 80% of identities
        // Uniform distribution in cold zone
        val hotPoolSize  = (numUsers.toDouble * hotFraction).toLong
        val coldPoolSize = numUsers - hotPoolSize
        val position     = (u - hotEventFraction) / (1.0 - hotEventFraction)
        hotPoolSize + (position * coldPoolSize.toDouble).toLong
      }
    }
}
