package com.snowplowanalytics.snowplow.eventgen.collector

import com.snowplowanalytics.snowplow.eventgen.base.{IpAddress, Url}
import org.scalacheck.Gen

import java.util.UUID
import java.time.Instant

/**
 * Information *derived* by the collector to be used as meta-data (meta-payload)
 * Everything else in [[CollectorPayload]] is directly payload (body and queryparams)
 *
 * @param timestamp  collector_tstamp (not optional in fact)
 * @param ipAddress  client's IP address, can be later overwritten by `ip` param in
 *                   `enrichments.Transform`
 * @param useragent  UA header, can be later overwritten by `ua` param in `entichments.Transform`
 * @param refererUri extracted from corresponding HTTP header
 * @param headers    all headers, including UA and referer URI
 * @param userId     generated by collector-set third-party cookie
 */
final case class CollectorContext(
                                   timestamp: Option[Instant],
                                   ipAddress: Option[IpAddress],
                                   useragent: Option[String],
                                   refererUri: Option[Url],
                                   userId: Option[UUID],
                                   headers: Headers
                                 )
{
  override def toString: String =
    s"""
       ts: $timestamp
       ip: $ipAddress
       ua: $useragent
       ref: ${refererUri.toString}
       uid: $userId
       headers: ${headers.toList.mkString("\n")}
       """.stripMargin
}

object CollectorContext {
  val gen: Gen[CollectorContext] = for {
    ts <- Gen.option(Instant.now())
    hdr <- Headers.gen
    ip <- IpAddress.genOpt
    uid <- Gen.some(Gen.uuid)
  } yield CollectorContext(ts, ip, hdr.ua, hdr.ref, uid, hdr)

}